/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-STOMP.h
 #	source generated by 4D Plugin Wizard
 #	Project : STOMP
 #	author : miyako
 #	2019/07/06
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_STOMP_H
#define PLUGIN_STOMP_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "ARRAY_TEXT.h"

#include "stomp.h"

#include <stdlib.h>
#include <map>
#include <mutex>

#pragma mark -

void STOMP_Connect(PA_PluginParameters params);
void STOMP_Read(PA_PluginParameters params);
void STOMP_Write(PA_PluginParameters params);
void STOMP_Disconnect(PA_PluginParameters params);

#endif /* PLUGIN_STOMP_H */
