/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : STOMP
 #	author : miyako
 #	2017/05/21
 #
 # --------------------------------------------------------------------------------*/


#include <stdlib.h>
#include "stomp.h"

// --- STOMP
void STOMP_Connect(sLONG_PTR *pResult, PackagePtr pParams);
void STOMP_Read(sLONG_PTR *pResult, PackagePtr pParams);
void STOMP_Write(sLONG_PTR *pResult, PackagePtr pParams);
void STOMP_Disconnect(sLONG_PTR *pResult, PackagePtr pParams);
